name: Scraper Canasta

permissions:
  contents: write

on:
  schedule:
    - cron: "15 5 12 * *"
    - cron: "15 5 13 * *"
    - cron: "15 5 14 * *"
    - cron: "15 5 15 * *"
  workflow_dispatch:

jobs:
  canasta:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper Canasta
        run: |
          python scrapers/scraper_canasta.py

      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/canasta
          git commit -m "chore: update canasta" || echo "No changes"
          git pull --rebase origin main
          git push
