name: CD - Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: xlmriosx/shared-library/.github/workflows/AWS-Lambda-deploy.yml@main
    with:
      ecr-repository: 'argly-api'
      function-name: 'argly-function'
      aws-region: 'sa-east-1'
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
