name: Scraper SMVM

permissions:
  contents: write

on:
  schedule:
    - cron: "0 5 5 * *" # Corre el 5 de cada mes a las 05:00 UTC
  push:
    paths:
      - "scrapers/smvm.py"
      - ".github/workflows/smvm.yml"
      - "requirements.txt"
  workflow_dispatch:

jobs:
  smvm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper SMVM
        run: |
          python scrapers/scraper_smvm.py

      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/smvm
          git commit -m "chore: update SMVM" || echo "No changes"
          git pull --rebase origin main
          git push
